### ISSUE TITLE
Configure a renovate bot for op-components 

### ISSUE THREAD

**Issue by hybridx** [1-Platform/op-components#13]
**Is your feature request related to a problem? Please describe.**
We currently have not added a renovate configuration to have dependencies updated periodically 

**Describe the solution you'd like**
Configure renovate to this repo so we can possible avoid possible security: Dependabot alerts

**Describe alternatives you've considered**
None

**Comment by hybridx** [comment]
@sayak-sarkar Can you configure for op-components as well?

**Comment by sayak-sarkar** [comment]
@hybridx Sure! I'll do it tonight!

**Comment by sayak-sarkar** [comment]
Done!
